Gitattrs
KnpLabs/Gaufrette pull request #679
Opened 2022-10-10 11:31 UTC by williamdes

Hi !
I did this change in two steps, first I excluded the files from the git archive: `git archive --help`. GitHub uses `git archive` for users to be able to "Download" a branch or git tag.

So I kept the test files and the phpunit config in it because: packing people on Debian/Alpine/Others... will download the source using scripts and do not want to have to clone your git history because they do not care about it and only want the source.
That said this is not what composer users want. They only want source file, so I excluded test files from the bundles that packagist produces.

Final users will only have source files, packaging people will have source+tests and devs can use git clone.
```sh
# Download source from my PR branch & extract
# composer install
~/Gaufrette-gitattrs$ ./vendor/bin/phpunit 
PHPUnit 8.5.30

SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS  63 / 207 ( 30%)
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS........ 126 / 207 ( 60%)
.........SSSSSSSSSSS........................................... 189 / 207 ( 91%)
..................                                              207 / 207 (100%)

Time: 131 ms, Memory: 12.00 MB

OK, but incomplete, skipped, or risky tests!
Tests: 207, Assertions: 170, Skipped: 129.
```

2022-10-12 19:29 UTC, Nek- requested changes
Thank you for your help on improving Gaufrette. This could be part of the next release (coming soon) but I think you may have excluded too much files if I follow the logic of your PR description.

2022-10-12 19:29 UTC, Nek- commented on composer.json
> +            "/phpunit.xml.dist"
spec folder and phpspec config file should be here to follow the logic entirely (it's part of the test suite). The .env.dist file is also absolutely required, as well as the make file.

2022-10-14 19:08 UTC, williamdes commented
> Thank you for your help on improving Gaufrette. This could be part of the next release (coming soon) but I think you may have excluded too much files if I follow the logic of your PR description.

Very cool !
I figured out that the Makefile without the docker files would not make sense so I also moved it for them. Should be okay now

2022-10-15 15:05 UTC, Nek- commented
> I figured out that the Makefile without the docker files would not make sense so I also moved it for them. Should be okay now

TBH there's a bit of cleanup to do about this... Many config files and build-related stuff are sooo outdated... Maybe gonna work on this.

But your work is nice thank you.

2022-10-15 15:05 UTC, Nek- approved these changes

2022-10-15 15:23 UTC, williamdes commented
> > I figured out that the Makefile without the docker files would not make sense so I also moved it for them. Should be okay now
> 
> TBH there's a bit of cleanup to do about this... Many config files and build-related stuff are sooo outdated... Maybe gonna work on this.
> 
> But your work is nice thank you.

Thank you, feel free to ping me for review on build stuff

2022-11-03 17:17 UTC, Nek- approved these changes

2022-11-03 17:17 UTC, merged

2022-11-03 17:27 UTC, Nek- commented
Thank you very much @williamdes !