Refactor/add type to file and filesystem
KnpLabs/Gaufrette pull request #696
Opened 2023-04-24 13:48 UTC by PedroTroller

2023-04-24 14:02 UTC, muchafm requested changes

2023-04-24 14:02 UTC, muchafm commented on src/Gaufrette/File.php
> +    public function getContent($metadata = []): string
```suggestion
    public function getContent(array $metadata): string
```

2023-04-24 14:02 UTC, muchafm commented on src/Gaufrette/File.php
> +    public function delete($metadata = []): bool
```suggestion
    public function delete(array $metadata): bool
```

2023-04-24 14:57 UTC, muchafm approved these changes

2023-05-25 12:36 UTC, KevinArtus approved these changes

2023-05-26 13:09 UTC, merged