Refacto: Add type on Stream classes
KnpLabs/Gaufrette pull request #698
Opened 2023-04-24 14:32 UTC by KevinArtus

2023-04-28 12:23 UTC, PedroTroller requested changes

2023-04-28 12:23 UTC, PedroTroller commented on src/Gaufrette/Stream.php
> +    public function seek(int $offset, int $whence = SEEK_SET): bool;
You can add `SEEK_SET|SEEK_CUR|SEEK_END` as `@param` for `$whence`

2023-04-28 12:23 UTC, PedroTroller commented on src/Gaufrette/Stream.php
> +    public function cast(int $castAs);
`$castAs` can be STREAM_CAST_FOR_SELECT or STREAM_CAST_AS_STREAM

2023-04-28 12:23 UTC, PedroTroller commented on src/Gaufrette/Stream/InMemoryBuffer.php
> +    private bool $synchronized;
I think only apply this typehint will create some troubles. For example, L191 will create failure instead of `return false` like currently.

2023-05-26 14:05 UTC, muchafm approved these changes

2023-06-30 13:58 UTC, PedroTroller commented on src/Gaufrette/Stream/Local.php
>      private $fileHandle;
Why not type these properties?

2023-10-23 15:34 UTC, closed without merging