refactor: add typeint to FilesystemMap, StreamWrapper and StreamMode
KnpLabs/Gaufrette pull request #699
Opened 2023-04-24 14:35 UTC by PedroTroller

2023-04-28 07:49 UTC, KevinArtus requested changes

2023-05-25 12:35 UTC, KevinArtus requested changes

2023-05-26 13:14 UTC, KevinArtus approved these changes

2023-05-26 13:45 UTC, muchafm approved these changes

2023-06-02 13:47 UTC, KevinArtus requested changes

2023-06-02 13:47 UTC, KevinArtus commented on src/Gaufrette/StreamWrapper.php
> +    public function url_stat(string $path, int $flags): array|bool
It's seems this method only return array

```
    /**
     * Gathers statistics of the stream.
     *
     * @return array
     */
    public function stat();
```

2023-10-23 15:34 UTC, closed without merging