refacto: spec types
KnpLabs/Gaufrette pull request #701
Opened 2023-04-28 12:46 UTC by muchafm

2023-05-12 08:02 UTC, Zusoy approved these changes

2023-05-25 12:11 UTC, KevinArtus requested changes

2023-05-25 12:11 UTC, KevinArtus commented on tests/Gaufrette/Functional/Adapter/AzureBlobStorageTest.php
>      /** @var AzureBlobStorage */
To remove

2023-05-25 12:11 UTC, KevinArtus commented on tests/Gaufrette/Functional/Adapter/AzureBlobStorageTest.php
>      /** @var string Name of the Azure container used */
```suggestion
    /** Name of the Azure container used */
```

2023-05-26 13:24 UTC, KevinArtus approved these changes

2023-05-26 13:24 UTC, PedroTroller requested changes

2023-05-26 13:24 UTC, PedroTroller commented on spec/Gaufrette/Adapter/functions.php
> -function apc_fetch($path)
Same: http://php.adamharvey.name/manual/en/function.apc-fetch.php

2023-05-26 13:24 UTC, PedroTroller commented on spec/Gaufrette/Adapter/functions.php
> -function apc_store($path, $content, $ttl)
Same: http://php.adamharvey.name/manual/en/function.apc-store.php

2023-05-26 13:24 UTC, PedroTroller commented on spec/Gaufrette/Adapter/functions.php
> -function apc_exists($path)
Same: http://php.adamharvey.name/manual/en/function.apc-exists.php

2023-06-30 14:01 UTC, PedroTroller approved these changes

2023-10-23 15:34 UTC, closed without merging