refacto: type filesystem and filesystem interface
KnpLabs/Gaufrette pull request #710
Opened 2023-10-30 14:54 UTC by KevinArtus

2023-10-30 15:01 UTC, muchafm requested changes

2023-10-30 15:01 UTC, muchafm commented on src/Gaufrette/Filesystem.php
> +    protected array $fileRegister = [];
c'est soit des strings(key et value) ou un File (string, File) visiblement

2023-10-30 15:02 UTC, PedroTroller requested changes

2023-10-30 15:02 UTC, PedroTroller commented on src/Gaufrette/FilesystemInterface.php
> +    public function createStream(string $key): Stream|Stream\InMemoryBuffer;
Stream\InMemoryBuffer is a Stream.

2023-10-30 15:04 UTC, PedroTroller requested changes

2023-10-30 15:04 UTC, PedroTroller commented on src/Gaufrette/Filesystem.php
> +    public function createStream(string $key): Stream|Stream\InMemoryBuffer
Same

2023-10-30 15:12 UTC, muchafm approved these changes

2024-02-26 10:49 UTC, muchafm approved these changes

2024-02-26 12:17 UTC, merged